### PR TITLE
Bump termcolor from 2.3 to 2.4

### PR DESCRIPTION
**Pull request by AkechiShiro**
Hi,

Is it possible to bump the version of termcolor as the latest release is the 2.4 release in December 2023.

### CODE REVIEW

**Review by alterakey — APPROVED** [review]
LGTM

**Comment by alterakey** [comment]
Hello @AkechiShiro , thank you for your PR! Merged.

**Comment by AkechiShiro** [comment]
Hi @alterakey is it possible to do a new release the package on our side is using the tag releases and currently is still using termcolor 2.4, is that something possible on your side ? Thanks !

**Comment by alterakey** [comment]
Sure @AkechiShiro , then how about if I release 2.1.9 with updated termcolor (as this PR) as 2.1.9.1? If it helps you, I would be happy to do so.

**Comment by AkechiShiro** [comment]
Yes that looks good to me, thanks a lot @alterakey for your help !

**Comment by AkechiShiro** [comment]
Yes that looks good to me, thanks a lot @alterakey for your help !

**Comment by alterakey** [comment]
Hi @AkechiShiro , I have released the termcolor update as 2.1.10. Have fun, and thanks for your PR. Keep up good work.

**Comment by alterakey** [comment]
Also updated PyPI.

**Pull request merged**
